name: Benchmarking
on:
  pull_request:
    branches: 'a'

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo test1

  test2:
    needs: test1
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo test2
