name: Benchmarking
on:
  pull_request

jobs:
  test1:
    if: github.head_ref matches '^[1-9][0-9]*\.[1-9][0-9]*$'
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo ${{ github.head_ref }}

  test2:
    needs: test1
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo test2
