name: Benchmarking ${{ inputs.reset-cache }}
on:
  workflow_dispatch:
    inputs:
      reset-cache:
        type: boolean
        default: true
  push:
    branches: main
  pull_request:
    branches: main
    #  schedule:
    #- cron: '1 * * * *'

jobs:
  modin-containerized:
    uses: ./.github/workflows/test-docker.yml

