name: Benchmarking
on:
  workflow_dispatch:
    inputs:
      reset-cache:
        type: boolean
        default: true
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '* * * * *'

jobs:
  modin-containerized:
    uses: ./.github/workflows/test-docker.yml

