name: Benchmarking
on:
  pull_request

jobs:
  test1:
#    if: false
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo ${{ github.head_ref }}

  test2:
    needs: test1
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo test2
